#!/usr/bin/env python3
"""
[Your Skill] Scaffold Tool

Two modes:
  detect   — scan a project directory and report what was found (language, gaps,
              existing config). Useful for agents before deciding what to generate.
  scaffold — write config/template files for the common case.
             For other cases, use detect output to guide manual generation.

TEMPLATE INSTRUCTIONS:
  1. Replace [YOUR_DOMAIN] references with your actual domain (e.g. "Kubernetes", "Terraform")
  2. Implement detect_project() to scan for indicators relevant to your domain
  3. Add your own TEMPLATES dict with file content for the scaffold command
  4. Adjust CLI arguments in main() to match your scaffold options
  5. Remove all TEMPLATE comments once done
"""

import sys
import json
import argparse
from pathlib import Path


# ---------------------------------------------------------------------------
# Templates
# Replace these with your actual file templates.
# Use {variable} placeholders that get filled in during scaffold.
# ---------------------------------------------------------------------------

# TEMPLATE: Add your file templates here
TEMPLATES: dict[str, str] = {
    "example-config.yml": """\
# Generated by scaffold.py
# Replace this with your actual template content
option: {option_value}
""",
}


# ---------------------------------------------------------------------------
# Detection
# Replace these with indicators relevant to your domain.
# ---------------------------------------------------------------------------

# TEMPLATE: Files whose presence indicates a particular language/framework
INDICATORS: dict[str, str] = {
    "requirements.txt": "python",
    "package.json":     "nodejs",
    "go.mod":           "go",
    # Add your own...
}


def detect_project(target: Path) -> dict:
    """
    Scan a project directory and return structured context.
    Output is designed to help an agent decide what to generate.

    TEMPLATE: Extend this to detect whatever is relevant to your domain.
    The returned dict is what the agent sees when you run `detect`.
    """
    result: dict = {
        "target":             str(target),
        "language":           None,
        "has_existing_config": False,
        "config_file":        None,
        "gaps":               [],
        "scaffold_supported": False,
    }

    files = {f.name for f in target.iterdir() if f.is_file()}

    # Language / framework detection
    for filename, lang in INDICATORS.items():
        if filename in files:
            result["language"] = lang
            break

    # Existing config detection
    # TEMPLATE: Replace "example-config.yml" with your actual config file name
    if "example-config.yml" in files:
        result["has_existing_config"] = True
        result["config_file"] = "example-config.yml"

    # Gap analysis
    result["gaps"] = _build_gap_list(result)

    # TEMPLATE: Set scaffold_supported based on what your scaffold command handles
    result["scaffold_supported"] = result["language"] == "python"

    return result


def _build_gap_list(result: dict) -> list[str]:
    """
    TEMPLATE: Return a list of human-readable gaps found in the project.
    These are shown to the agent so it knows what needs to be fixed/generated.
    """
    gaps = []
    if not result["has_existing_config"]:
        gaps.append("no config file found")
    if not result["language"]:
        gaps.append("could not detect language")
    return gaps


# ---------------------------------------------------------------------------
# Scaffold
# ---------------------------------------------------------------------------

class Scaffolder:
    """
    TEMPLATE: Generates files for the common case.
    Add parameters that vary between projects (version, group, options, etc.)
    """

    def __init__(
        self,
        target: str,
        option_value: str = "default",   # TEMPLATE: Replace with your own options
        dry_run: bool = False,
        verbose: bool = False,
    ):
        self.target = Path(target)
        self.option_value = option_value
        self.dry_run = dry_run
        self.verbose = verbose
        self.generated: list[str] = []

    def run(self) -> dict:
        if not self.target.exists():
            raise ValueError(f"Target path does not exist: {self.target}")

        # TEMPLATE: Call _write() for each file you want to generate
        self._write(
            "example-config.yml",
            TEMPLATES["example-config.yml"].format(option_value=self.option_value),
        )

        return {"generated": self.generated, "target": str(self.target)}

    def _write(self, rel_path: str, content: str) -> None:
        dest = self.target / rel_path
        if self.verbose or self.dry_run:
            print(f"  {'[dry-run] ' if self.dry_run else ''}write → {dest}")
        if not self.dry_run:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content)
        self.generated.append(str(dest))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="[Your Skill] tool — detect project context or scaffold config files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
commands:
  detect    scan a project directory and report language, gaps, and recommendations
  scaffold  write config files for the common case

examples:
  %(prog)s detect ./my-project
  %(prog)s detect ./my-project --json
  %(prog)s scaffold ./my-project --option-value custom --dry-run
""",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # detect
    p_detect = subparsers.add_parser("detect", help="Scan project and report context")
    p_detect.add_argument("target", help="Project directory to scan")
    p_detect.add_argument("--json", action="store_true", dest="output_json")

    # scaffold — TEMPLATE: Add your own arguments here
    p_scaffold = subparsers.add_parser("scaffold", help="Generate config files")
    p_scaffold.add_argument("target", help="Target project directory")
    p_scaffold.add_argument("--option-value", default="default", metavar="VAL")
    p_scaffold.add_argument("--dry-run", action="store_true")
    p_scaffold.add_argument("--verbose", "-v", action="store_true")
    p_scaffold.add_argument("--json", action="store_true", dest="output_json")

    args = parser.parse_args()

    try:
        if args.command == "detect":
            target = Path(args.target)
            if not target.exists():
                raise ValueError(f"Path does not exist: {target}")
            result = detect_project(target)
            if args.output_json:
                print(json.dumps(result, indent=2))
            else:
                _print_detection(result)

        elif args.command == "scaffold":
            gen = Scaffolder(
                target=args.target,
                option_value=args.option_value,
                dry_run=args.dry_run,
                verbose=args.verbose,
            )
            result = gen.run()
            if args.output_json:
                print(json.dumps(result, indent=2))
            else:
                action = "Would generate" if args.dry_run else "Generated"
                print(f"{action} {len(result['generated'])} files in {result['target']}")
                if args.verbose or args.dry_run:
                    for f in result["generated"]:
                        print(f"  {f}")

    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def _print_detection(r: dict) -> None:
    print(f"Target:   {r['target']}")
    print(f"Language: {r['language'] or 'unknown'}")
    print(f"Config:   {r['config_file'] or 'none'}")
    if r["gaps"]:
        print("Gaps:")
        for g in r["gaps"]:
            print(f"  - {g}")
    print(f"Scaffold: {'supported' if r['scaffold_supported'] else 'not supported — use SKILL.md patterns for manual generation'}")


if __name__ == "__main__":
    main()
